### ISSUE TITLE
Cannot scrape members, Error showing!

### ISSUE THREAD

**Issue by AdityaDas5501** [Amanbytes/auto-add-members-in-telegram-groups-and-channels#7]
Traceback (most recent call last):
  File "D:\PycharmProjects\Telegram_bos\Test.py", line 198, in <module>
    list_users_in_group()
  File "D:\PycharmProjects\Telegram_bos\Test.py", line 147, in list_users_in_group
    all_participants = client.get_participants(target_group, aggressive=True)
  File "D:\PycharmProjects\Telegram_bos\venv\lib\site-packages\telethon\sync.py", line 39, in syncified
    return loop.run_until_complete(coro)
  File "D:\Python\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "D:\PycharmProjects\Telegram_bos\venv\lib\site-packages\telethon\client\chats.py", line 507, in get_participants
    return await self.iter_participants(*args, **kwargs).collect()
  File "D:\PycharmProjects\Telegram_bos\venv\lib\site-packages\telethon\requestiter.py", line 113, in collect
    async for message in self:
  File "D:\PycharmProjects\Telegram_bos\venv\lib\site-packages\telethon\requestiter.py", line 74, in __anext__
    if await self._load_next_chunk():
  File "D:\PycharmProjects\Telegram_bos\venv\lib\site-packages\telethon\client\chats.py", line 222, in _load_next_chunk
    results = await self.client(self.requests)
  File "D:\PycharmProjects\Telegram_bos\venv\lib\site-packages\telethon\client\users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "D:\PycharmProjects\Telegram_bos\venv\lib\site-packages\telethon\client\users.py", line 80, in _call
    raise MultiError(exceptions, results, requests)
telethon.errors.common.MultiError: ([None, None, None, FloodWaitError('A wait of 31 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 31 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 31 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 31 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 31 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 31 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 31 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 31 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 31 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 31 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 31 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 31 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 31 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 31 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 31 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 31 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 31 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 31 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 31 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 31 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 31 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 31 seconds is required (caused by GetParticipantsRequest)')], [<telethon.tl.types.channels.ChannelParticipants object at 0x000002142D19E100>, <telethon.tl.types.channels.ChannelParticipants object at 0x000002142D19EDF0>, <telethon.tl.types.channels.ChannelParticipants object at 0x000002142D19E040>, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None], [<telethon.tl.functions.channels.GetParticipantsRequest object at 0x000002142D16AE50>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x000002142D16AF10>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x000002142D16AFD0>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x000002142D16E0D0>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x000002142D16E190>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x000002142D16E250>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x000002142D16E310>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x000002142D16E3D0>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x000002142D16E490>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x000002142D16E550>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x000002142D16E610>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x000002142D16E6D0>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x000002142D16E790>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x000002142D16E850>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x000002142D16E910>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x000002142D16E9D0>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x000002142D16EB50>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x000002142D16EC10>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x000002142D16ECD0>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x000002142D16ED90>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x000002142D16EE50>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x000002142D16EF10>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x000002142D16EFD0>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x000002142D1700D0>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x000002142D170190>])

**Comment by alpenliebeanj** [comment]
I have the same issue
